<?php
// Special Operators
/*
[and] Accesses an element of an array.
=> Specifies the index or key of an array element.
, Seperates arguments in a list
? and : Executes one of two expressions based
on the results of a conditional expression

instanceof  Returns TRUE if an object is of a specified object type

@   Suppresses any errors that might be generated by an expression
    to which it is prepended (or placed before)

(int), (integer),   Casts (or transforms) a variable of aone data 
(bool), (boolean),  type into a variable of another data type. 
(double), (string), 
(array), (object)
*/

?>

